version: "3.9"

services:
  data-collector:
    build:
      context: .
      dockerfile: services/data_collector/Dockerfile
    env_file:
      - ./services/data_collector/.env
    volumes:
      - ./logs:/app/logs
    command: python -m yieldex_data_collector.collector