services:
  data-collector:
    build:
      context: .
      dockerfile: services/data_collector/Dockerfile
    env_file:
      - ./services/data_collector/.env
    volumes:
      - ./logs:/app/logs
    environment:
      - CONFIG_PATH=/app/data_collector/config.yaml
      - LOG_DIR=/app/logs
      - PYTHONUNBUFFERED=1